# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UrbanAreaDemand
                                 A QGIS plugin
 Urban Area Demand
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-24
        copyright            : (C) 2023 by GALUP
        email                : koreyarsenault@ufl.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UrbanAreaDemand class from file UrbanAreaDemand.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .urb_demand import UrbanAreaDemand
    return UrbanAreaDemand(iface)
